services:
  - type: web
    name: stockmind-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000
    plan: free